name: Working with Inputs

on:
  push: 
      
jobs:
  build:
    outputs:
      variableSalida: "mi Valor"
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building from tag "

  deploy:
    runs-on: ubuntu-latest
    needs: build      
    steps:
      - name: Deploy
        run: echo "Variable es ${{needs.build.outputs.variableSalida}}" 
