name: Working with Inputs

on:  
  workflow_dispatch: 
    inputs:
      num1: 
       type: number
       description: un numero
      num2: 
       type: number
       description: otro numero
      
jobs:
  build:
    outputs:
      salidaJobsuma: ${{steps.suma.outputs.SUMA}}
      salidaJobResta: ${{steps.suma.outputs.RESTA}}
    runs-on: ubuntu-latest
    steps:
      - name: Suma
        id: suma
        run: echo "SUMA=$(( ${{ inputs.num1 }} + ${{ inputs.num2 }} ))" > "$GITHUB_OUTPUT"
       
      - name: Resta
        id: resta
        run: echo "RESTA=$(( ${{ inputs.num1 }} - ${{ inputs.num2 }} ))" > "$GITHUB_OUTPUT"

  deploy:
   runs-on: ubuntu-latest
   needs: build      
   steps:
     - name: Pintar suma
       run: echo "La suma es ${{needs.build.outputs.salidaJobsuma}}" 
     
     - name: Pintar resta
       run: echo "La suma es ${{needs.build.outputs.salidaJobResta}}" 
